import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: "#f4f6f9",
  },
  searchInput: {
    height: 45,
    borderColor: "#d1d8e0",
    backgroundColor: "#ffffff",
    color: "#333333",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 15,
    marginVertical: 12,
  },
  bannerContainer: {
    alignItems: "center",
    marginVertical: 15,
  },
  categoryTab: {
    marginRight: 15,
    position: "relative",
    borderRadius: 12,
    overflow: "hidden",
  },
  categoryImageContainer: {
    width: 160,
    height: 100,
    position: "relative",
    borderRadius: 12,
  },
  categoryImage: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
    position: "absolute",
    top: 0,
    left: 0,
  },
  categoryText: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: "-50%" }, { translateY: " -50%" }],
    fontSize: 16,
    fontWeight: "bold",
    color: "#ffffff",
    textShadowColor: "#000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  activeCategoryTab: {
    backgroundColor: "#4a90e2",
  },
  bannerImage: {
    width: 365,
    height: 200,
    borderRadius: 12,
    marginRight: 20,
  },
  categoryTabContainer: {
    flexDirection: "row",
    marginVertical: 15,
  },
  categoryTabText: {
    color: "#333333",
    fontWeight: "600",
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333333",
    marginVertical: 15,
  },
  productContainer: {
    paddingBottom: 20,
    alignItems: "center",
  },
  card: {
    width: 180,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 10,
    marginHorizontal: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 0.3,
    marginBottom: 20,
    shadowOffset: { width: 0, height: 5 },
  },
  cardImage: {
    width: "100%",
    height: 140,
    borderRadius: 8,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 16,
    textAlign: "left",
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 5,
  },
  cardDescription: {
    fontSize: 14,
    color: "#666666",
    marginBottom: 8,
    textAlign: "center",
  },
  cardPrice: {
    fontSize: 16,
    fontWeight: "600",
    color: "#007bff",
    marginBottom: 8,
  },
  cardColor: {
    fontSize: 12,
    color: "#888888",
    marginBottom: 4,
  },
  cardPassengers: {
    fontSize: 12,
    color: "#888888",
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 30,
  },
  title: {
    fontSize: 32,
    fontWeight: "800",
    color: "#333",
    marginBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: "#e0e0e0",
    paddingBottom: 10,
  },
  productImage: {
    width: "100%",
    height: 400,
    resizeMode: "cover",
    borderRadius: 15,
    marginBottom: 20,
    backgroundColor: "#f4f4f4",
    borderWidth: 2,
    borderColor: "#e0e0e0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  productTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#333",
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    paddingBottom: 5,
  },
  productCategory: {
    fontSize: 18,
    fontWeight: "500",
    color: "#FF6347",
    marginBottom: 15,
    textTransform: "uppercase",
  },
  productDescription: {
    fontSize: 16,
    color: "#666",
    lineHeight: 24,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: "#6c63ff",
    paddingLeft: 15,
  },
  sectionTitleDetail: {
    fontSize: 20,
    fontWeight: "600",
    color: "#333",
    marginTop: 25,
    marginBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: "#e0e0e0",
  },
  productText: {
    fontSize: 16,
    color: "#666",
    lineHeight: 24,
    marginBottom: 10,
  },
  addToCartButton: {
    paddingVertical: 14,
    paddingHorizontal: 30,
    backgroundColor: "#6c63ff",
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: "#6c63ff",
  },
  addToCartButtonText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#fff",
  },
  goBackButton: {
    paddingVertical: 12,
    paddingHorizontal: 30,
    backgroundColor: "#e0e0e0",
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  goBackButtonText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333",
  },
  categorySection: {
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  categoryTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginVertical: 10,
  },
  noProductsText: {
    textAlign: "center",
    color: "#888",
    fontSize: 14,
    marginVertical: 10,
  },
});
